const PgpKey = () => {
    const pgp_key = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEZlAP1hYJKwYBBAHaRw8BAQdAaitYgmKXNOK6boJRw7EIXTVF9J6Myxv8
c564p7ioXNXNJ2FtZWtuaXRlQHByb3Rvbi5tZSA8YW1la25pdGVAcHJvdG9u
Lm1lPsKMBBAWCgA+BYJmUA/WBAsJBwgJkFNGmhEqxo1eAxUICgQWAAIBAhkB
ApsDAh4BFiEEuxBQ8GF1GeXi2mjKU0aaESrGjV4AAORnAP95H7WYvhAITHYU
IkUi3LRPkUlPi7ohe1+XASZOvDK37wEAq1oF/hAA86SFrfFg2nI0dh5AuAdW
toKXEjV7OqbpjwzOOARmUA/WEgorBgEEAZdVAQUBAQdAQPsURQuzRTVpQkS2
wLVxxXcZ4zXdKoB1YTVdSX7RLlQDAQgHwncEGBYKACoFgmZQD9YJkFNGmhEq
xo1eApsMFiEEuxBQ8GF1GeXi2mjKU0aaESrGjV4AANuNAPwN7eUedb5y3os9
jHHXAs3jnl0SLVAFj+jnQlwba09SngD45eNERR2lPQq5lFT6GheM2QoBC9VI
M4HbLEf969rzCw==
=Kn19
-----END PGP PUBLIC KEY BLOCK-----`;
    return (
        <pre>
            {pgp_key}
        </pre>
    );
};

export default PgpKey;
